# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class I16Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # I16Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # I16Entry
    def Idx(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # I16Entry
    def Val(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateI16Entry(builder, idx, val):
    builder.Prep(2, 4)
    builder.PrependInt16(val)
    builder.PrependUint16(idx)
    return builder.Offset()


class I16EntryT(object):

    # I16EntryT
    def __init__(
        self,
        idx = 0,
        val = 0,
    ):
        self.idx = idx  # type: int
        self.val = val  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        i16Entry = I16Entry()
        i16Entry.Init(buf, pos)
        return cls.InitFromObj(i16Entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, i16Entry):
        x = I16EntryT()
        x._UnPack(i16Entry)
        return x

    # I16EntryT
    def _UnPack(self, i16Entry):
        if i16Entry is None:
            return
        self.idx = i16Entry.Idx()
        self.val = i16Entry.Val()

    # I16EntryT
    def Pack(self, builder):
        return CreateI16Entry(builder, self.idx, self.val)
