# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class I32Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # I32Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # I32Entry
    def Idx(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # I32Entry
    def Val(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateI32Entry(builder, idx, val):
    builder.Prep(4, 8)
    builder.PrependInt32(val)
    builder.Pad(2)
    builder.PrependUint16(idx)
    return builder.Offset()


class I32EntryT(object):

    # I32EntryT
    def __init__(
        self,
        idx = 0,
        val = 0,
    ):
        self.idx = idx  # type: int
        self.val = val  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        i32Entry = I32Entry()
        i32Entry.Init(buf, pos)
        return cls.InitFromObj(i32Entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, i32Entry):
        x = I32EntryT()
        x._UnPack(i32Entry)
        return x

    # I32EntryT
    def _UnPack(self, i32Entry):
        if i32Entry is None:
            return
        self.idx = i32Entry.Idx()
        self.val = i32Entry.Val()

    # I32EntryT
    def Pack(self, builder):
        return CreateI32Entry(builder, self.idx, self.val)
