# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class I64Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # I64Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # I64Entry
    def Idx(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # I64Entry
    def Val(self): return self._tab.Get(flatbuffers.number_types.Int64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateI64Entry(builder, idx, val):
    builder.Prep(8, 16)
    builder.PrependInt64(val)
    builder.Pad(6)
    builder.PrependUint16(idx)
    return builder.Offset()


class I64EntryT(object):

    # I64EntryT
    def __init__(
        self,
        idx = 0,
        val = 0,
    ):
        self.idx = idx  # type: int
        self.val = val  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        i64Entry = I64Entry()
        i64Entry.Init(buf, pos)
        return cls.InitFromObj(i64Entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, i64Entry):
        x = I64EntryT()
        x._UnPack(i64Entry)
        return x

    # I64EntryT
    def _UnPack(self, i64Entry):
        if i64Entry is None:
            return
        self.idx = i64Entry.Idx()
        self.val = i64Entry.Val()

    # I64EntryT
    def Pack(self, builder):
        return CreateI64Entry(builder, self.idx, self.val)
