# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class I8Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # I8Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # I8Entry
    def Idx(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # I8Entry
    def Val(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateI8Entry(builder, idx, val):
    builder.Prep(2, 4)
    builder.Pad(1)
    builder.PrependInt8(val)
    builder.PrependUint16(idx)
    return builder.Offset()


class I8EntryT(object):

    # I8EntryT
    def __init__(
        self,
        idx = 0,
        val = 0,
    ):
        self.idx = idx  # type: int
        self.val = val  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        i8Entry = I8Entry()
        i8Entry.Init(buf, pos)
        return cls.InitFromObj(i8Entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, i8Entry):
        x = I8EntryT()
        x._UnPack(i8Entry)
        return x

    # I8EntryT
    def _UnPack(self, i8Entry):
        if i8Entry is None:
            return
        self.idx = i8Entry.Idx()
        self.val = i8Entry.Val()

    # I8EntryT
    def Pack(self, builder):
        return CreateI8Entry(builder, self.idx, self.val)
