# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

class StatusCode(object):
    OK = 0
    Unauthorized = 1
    BadRequest = 2
    ServiceUnavailable = 3
    InternalServerError = 4
