# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class U16Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # U16Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # U16Entry
    def Idx(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # U16Entry
    def Val(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateU16Entry(builder, idx, val):
    builder.Prep(2, 4)
    builder.PrependUint16(val)
    builder.PrependUint16(idx)
    return builder.Offset()


class U16EntryT(object):

    # U16EntryT
    def __init__(
        self,
        idx = 0,
        val = 0,
    ):
        self.idx = idx  # type: int
        self.val = val  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        u16Entry = U16Entry()
        u16Entry.Init(buf, pos)
        return cls.InitFromObj(u16Entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, u16Entry):
        x = U16EntryT()
        x._UnPack(u16Entry)
        return x

    # U16EntryT
    def _UnPack(self, u16Entry):
        if u16Entry is None:
            return
        self.idx = u16Entry.Idx()
        self.val = u16Entry.Val()

    # U16EntryT
    def Pack(self, builder):
        return CreateU16Entry(builder, self.idx, self.val)
