# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class U32Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # U32Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # U32Entry
    def Idx(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # U32Entry
    def Val(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateU32Entry(builder, idx, val):
    builder.Prep(4, 8)
    builder.PrependUint32(val)
    builder.Pad(2)
    builder.PrependUint16(idx)
    return builder.Offset()


class U32EntryT(object):

    # U32EntryT
    def __init__(
        self,
        idx = 0,
        val = 0,
    ):
        self.idx = idx  # type: int
        self.val = val  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        u32Entry = U32Entry()
        u32Entry.Init(buf, pos)
        return cls.InitFromObj(u32Entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, u32Entry):
        x = U32EntryT()
        x._UnPack(u32Entry)
        return x

    # U32EntryT
    def _UnPack(self, u32Entry):
        if u32Entry is None:
            return
        self.idx = u32Entry.Idx()
        self.val = u32Entry.Val()

    # U32EntryT
    def Pack(self, builder):
        return CreateU32Entry(builder, self.idx, self.val)
