# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class U64Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # U64Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # U64Entry
    def Idx(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # U64Entry
    def Val(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateU64Entry(builder, idx, val):
    builder.Prep(8, 16)
    builder.PrependUint64(val)
    builder.Pad(6)
    builder.PrependUint16(idx)
    return builder.Offset()


class U64EntryT(object):

    # U64EntryT
    def __init__(
        self,
        idx = 0,
        val = 0,
    ):
        self.idx = idx  # type: int
        self.val = val  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        u64Entry = U64Entry()
        u64Entry.Init(buf, pos)
        return cls.InitFromObj(u64Entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, u64Entry):
        x = U64EntryT()
        x._UnPack(u64Entry)
        return x

    # U64EntryT
    def _UnPack(self, u64Entry):
        if u64Entry is None:
            return
        self.idx = u64Entry.Idx()
        self.val = u64Entry.Val()

    # U64EntryT
    def Pack(self, builder):
        return CreateU64Entry(builder, self.idx, self.val)
