# automatically generated by the FlatBuffers compiler, do not modify

# namespace: infolog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class U8Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # U8Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # U8Entry
    def Idx(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # U8Entry
    def Val(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateU8Entry(builder, idx, val):
    builder.Prep(2, 4)
    builder.Pad(1)
    builder.PrependUint8(val)
    builder.PrependUint16(idx)
    return builder.Offset()


class U8EntryT(object):

    # U8EntryT
    def __init__(
        self,
        idx = 0,
        val = 0,
    ):
        self.idx = idx  # type: int
        self.val = val  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        u8Entry = U8Entry()
        u8Entry.Init(buf, pos)
        return cls.InitFromObj(u8Entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, u8Entry):
        x = U8EntryT()
        x._UnPack(u8Entry)
        return x

    # U8EntryT
    def _UnPack(self, u8Entry):
        if u8Entry is None:
            return
        self.idx = u8Entry.Idx()
        self.val = u8Entry.Val()

    # U8EntryT
    def Pack(self, builder):
        return CreateU8Entry(builder, self.idx, self.val)
