/*
{
    "type": "sp_mv",
    "version": "070600.3329",
    "name": "fv_fgt_t_src_dst",
    "datasource_mv": "fv_fgt_t_src_dst_5min_mv_sp$SPID"
}
*/
DROP TABLE IF EXISTS siem.fv_fgt_t_src_dst_5min_mv_sp$SPID;
DROP TABLE IF EXISTS siem.fv_fgt_t_src_dst_hour_mv_sp$SPID;
DROP TABLE IF EXISTS siem.fv_fgt_t_src_dst_day_mv_sp$SPID;
DROP TABLE IF EXISTS siem.fv_fgt_t_src_dst_5min_sp$SPID;
DROP TABLE IF EXISTS siem.fv_fgt_t_src_dst_hour_sp$SPID;
DROP TABLE IF EXISTS siem.fv_fgt_t_src_dst_day_sp$SPID;

CREATE TABLE IF NOT EXISTS siem.fv_fgt_t_src_dst_5min_sp$SPID (
    timescale DateTime, dvid Int32, f_user Nullable(String), group_info Nullable(String),
    _adomoid UInt64,
    flags UInt32,
    d_flags UInt32,
    srcmac Nullable(String),
    srcip Nullable(IPv6),
    srcintf LowCardinality(Nullable(String)),
    srcintfrole LowCardinality(Nullable(String)),
    srcuuid Nullable(UUID) CODEC(LZ4),
    srcinetsvc Nullable(String) CODEC(LZ4),
    dstmac Nullable(String),
    dstip Nullable(IPv6),
    dstintf LowCardinality(Nullable(String)),
    dstintfrole LowCardinality(Nullable(String)),
    dstowner LowCardinality(Nullable(String)),
    dstuuid Nullable(UUID),
    dstcountry LowCardinality(Nullable(String)),
    epid Int32,
    clientdevicetags Nullable(String),
    dev_src  Nullable(String),
    devtype Nullable(String),
    app_group Nullable(String),
    rulename Nullable(String),
    vwlid Nullable(UInt32),
    domain Nullable(String),
    hostname Nullable(String),
    catdesc LowCardinality(Nullable(String)),
    policymode LowCardinality(Nullable(String)),
    policyid Nullable(UInt32),
	policytype LowCardinality(Nullable(String)),
    poluuid Nullable(UUID),
    policyname Nullable(String),
    service LowCardinality(Nullable(String)),
    accessproxy Nullable(String),
    saasname Nullable(String),
    fctuid Nullable(UUID),
    avatar_state  AggregateFunction(max, Nullable(String)),
    epeuid_state  AggregateFunction(max, Nullable(String)),
    logtime_state AggregateFunction(max, DateTime), threatlvl_state AggregateFunction(max, Int8),
    threatweight_state AggregateFunction(sum, Int64), threatblock_state AggregateFunction(sum, Int64),
    thwgt_cri_state AggregateFunction(sum, Int64), thwgt_hig_state AggregateFunction(sum, Int64),
    thwgt_med_state AggregateFunction(sum, Int64), thwgt_low_state AggregateFunction(sum, Int64),
    bandwidth_state AggregateFunction(sum, Int64), traffic_in_state AggregateFunction(sum, Int64),
    traffic_out_state AggregateFunction(sum, Int64), session_block_state AggregateFunction(sum, Int64),
    browse_time_state AggregateFunction(browseTime, UInt64),
    sessions_state AggregateFunction(sum, Int64)
)
ENGINE = AggregatingMergeTree()
PRIMARY KEY (_adomoid, dvid, timescale, srcintfrole, dstintfrole)
ORDER BY (_adomoid, dvid, timescale, srcintfrole, dstintfrole, devtype, dev_src, srcip, dstip, dstmac,
         epid, f_user, group_info, srcintf, dstintf, dstowner, dstcountry,
         srcuuid, srcmac, srcinetsvc, dstuuid, app_group, rulename, vwlid, flags, d_flags,
         catdesc, policymode, policyid, policytype, poluuid,
         policyname, service, domain, hostname, fctuid,
         accessproxy, saasname, clientdevicetags)
PARTITION BY toYYYYMMDD(timescale)
SETTINGS index_granularity = 8192, allow_nullable_key = 1 $STORAGE;


CREATE TABLE IF NOT EXISTS siem.fv_fgt_t_src_dst_hour_sp$SPID AS siem.fv_fgt_t_src_dst_5min_sp$SPID;


CREATE TABLE IF NOT EXISTS siem.fv_fgt_t_src_dst_day_sp$SPID AS siem.fv_fgt_t_src_dst_5min_sp$SPID;


CREATE MATERIALIZED VIEW IF NOT EXISTS siem.fv_fgt_t_src_dst_5min_mv_sp$SPID
TO siem.fv_fgt_t_src_dst_5min_sp$SPID
AS SELECT _adomoid, dvid,
       fv_timescale_func(itime, 300, 0) AS timescale,
       epid,
       coalesce(nullifna(user), nullifna(unauthuser)) AS f_user,
       `group` AS group_info,
       dev_src,
       srcmac,
       srcip,
       srcintf,
       srcintfrole,
       srcuuid,
       srcinetsvc,
       dstip,
       dstmac,
       dstintf,
       dstintfrole,
       dstuuid,
       dstowner,
       dstcountry,
       clientdevicetags,
       devtype,
       flags,
       d_flags,
       app_group,
       rulename,
       vwlid,
       domain,
       hostname,
       catdesc,
       policymode,
       policyid,
       policytype,
       poluuid,
       policyname,
       service,
       accessproxy,
       saasname,
       fctuid,
       maxState(avatar) AS avatar_state,
       maxState(epeuid) AS epeuid_state, maxState(dtime) AS logtime_state,
       maxState(threatlvl) AS threatlvl_state, sumState(threatwgt) AS threatweight_state,
       sumState(threat_block) AS threatblock_state,
       sumState(thwgt_cri) AS thwgt_cri_state, sumState(thwgt_hig) AS thwgt_hig_state,
       sumState(thwgt_med) AS thwgt_med_state, sumState(thwgt_low) AS thwgt_low_state,
       sumState(toInt64(bandwidth)) AS bandwidth_state, sumState(toInt64(traffic_in)) AS traffic_in_state,
       sumState(toInt64(traffic_out)) AS traffic_out_state, sumState(session_block) AS session_block_state,
       browseTimeStateArray(ebtime) AS browse_time_state,
       sumState(sessions) AS sessions_state
    FROM (
       SELECT
           itime,
           dvid,
           epid,
           _adomoid,
           _devlogtype,
           $LOGFIELD-clientdevicetags,
           $LOGFIELD-user,
           $LOGFIELD-unauthuser,
           $LOGFIELD-group,
           $LOGFIELD-srcmac,
           $LOGFIELD-srcip,
           $LOGFIELD-srcintf,
           $LOGFIELD-srcintfrole,
           $LOGFIELD-srcuuid,
           $LOGFIELD-srcname,
           $LOGFIELD-srcinetsvc,
           coalesce(srcname, srcmac) AS dev_src,
           $LOGFIELD-dstmac,
           $LOGFIELD-dstip,
           $LOGFIELD-dstintf,
           $LOGFIELD-dstintfrole,
           $LOGFIELD-dstuuid,
           $LOGFIELD-dstowner,
           $LOGFIELD-srcswversion,
           $LOGFIELD-osname,
           $LOGFIELD-devtype-t_devtype,
           get_devtype(srcswversion, osname, t_devtype) devtype,
           $LOGFIELD-dstcountry,
           $LOGFIELD-app, 
           $LOGFIELD-vwlname, 
           $LOGFIELD-vwlservice, 
           $LOGFIELD-vwlid,
           $LOGFIELD-catdesc,
           $LOGFIELD-policymode,
           $LOGFIELD-policyid,
           $LOGFIELD-policytype,
           $LOGFIELD-poluuid,
           $LOGFIELD-policyname,
           $LOGFIELD-service, coalesce(vwlname,vwlservice) AS rulename,
           app_group_name(app) AS app_group,
           $LOGFIELD-hostname,
           logflag, 
           $LOGFIELD-unauthuser,
           (CASE WHEN(bitAnd(logflag, 64) > 0) THEN hostname ELSE root_domain(hostname) END) AS domain, hostname,
           $LOGFIELD-accessproxy,
           $LOGFIELD-saasname,
           $LOGFIELD-fctuid,
           $LOGFIELD-appcat,
           multiIf(bitAnd(logflag, 64) > 0, 2, 0) AS flags_a,
           multiIf(appcat='unscanned',1,0) AS flags_b,
           bitOr(flags_a,flags_b) AS flags,
           (CASE WHEN appcat='unscanned' THEN 1 ELSE 0 END) AS d_flags, 
           (CASE WHEN $LOGFIELD_NOALIAS-fctuid IS NOT NULL AND unauthuser IS NOT NULL THEN CONCAT(toString($LOGFIELD_NOALIAS-fctuid), ',', unauthuser) ELSE NULL END) AS avatar,
           ( CASE WHEN epid > 1023 AND euid != 0 THEN CONCAT(toString(epid), ',', toString(euid)) ELSE NULL END) AS epeuid,
           $LOGFIELD-ebtime,
           dtime,
           $LOGFIELD-threatlvls,
           $LOGFIELD-threatwgts,
           $LOGFIELD-threatcnts,
           threatlevel_max(threatlvls) AS threatlvl,
           threatweight_sum(threatwgts, threatcnts) AS threatwgt,
           ( CASE WHEN(bitAnd(logflag, 2) > 0) THEN threatwgt ELSE 0 END) AS threat_block, 
           threatweight_level_sum(4,threatlvls,threatcnts,threatwgts) AS thwgt_cri,
           threatweight_level_sum(3,threatlvls,threatcnts,threatwgts) AS thwgt_hig,
           threatweight_level_sum(2,threatlvls,threatcnts,threatwgts) AS thwgt_med,
           threatweight_level_sum(1,threatlvls,threatcnts,threatwgts) AS thwgt_low,
           $LOGFIELD-sentbyte,
           $LOGFIELD-rcvdbyte, 
           $LOGFIELD-sentdelta,
           $LOGFIELD-rcvddelta,
           coalesce(sentdelta, sentbyte, 0)+coalesce(rcvddelta, rcvdbyte, 0) AS bandwidth,
           coalesce(rcvddelta, rcvdbyte, 0) AS traffic_in,
           coalesce(sentdelta, sentbyte, 0) AS traffic_out,
           CAST(( CASE WHEN(bitAnd(logflag, 2) > 0) THEN 1 ELSE 0 END), 'Int64') AS session_block, 
           CAST(( CASE WHEN(bitAnd(logflag, 1) > 0) THEN 1 ELSE 0 END), 'Int64') AS sessions
      FROM siem.tlog_sp$SPID
      WHERE bitAnd(logflag, bitOr(1, 32)) > 0 AND _devlogtype = 10
)
GROUP BY _adomoid, dvid, timescale,
     epid, f_user, group_info, devtype,
     srcmac, srcip, srcintf, srcintfrole, srcuuid, srcinetsvc, dev_src,
     dstip, dstmac, dstintf, dstintfrole, dstuuid, dstowner, dstcountry,
     app_group, rulename, vwlid, flags, d_flags, catdesc,
     policymode, policyid, policytype, poluuid, policyname,
     service, domain, hostname, fctuid,
     accessproxy, saasname, clientdevicetags;


CREATE MATERIALIZED VIEW IF NOT EXISTS siem.fv_fgt_t_src_dst_hour_mv_sp$SPID
TO siem.fv_fgt_t_src_dst_hour_sp$SPID
AS SELECT dvid,
       fv_timescale_func(timescale, 3600, 0) AS timescale,
       epid,
       _adomoid,
       flags,
       d_flags,
       f_user,
       srcmac,
       srcip,
       srcintf,
       srcintfrole,
       srcuuid,
       srcinetsvc,
       dstip,
       dstmac,
       dstintf,
       dstintfrole,
       dstuuid,
       dstowner,
       dstcountry,
       group_info,
       dev_src,
       devtype,
       app_group,
       rulename,
       vwlid,
       domain,
       hostname,
       catdesc,
       policymode,
       policyid,
       policytype,
       poluuid,
       policyname,
       service,
       clientdevicetags,
       accessproxy,
       saasname,
       fctuid,
        maxState(avatar) AS avatar_state,
       maxState(epeuid) AS epeuid_state, maxState(logtime) AS logtime_state,
       maxState(threatlvl) AS threatlvl_state, sumState(threatwgt) AS threatweight_state,
       sumState(threat_block) AS threatblock_state,
       sumState(thwgt_cri) AS thwgt_cri_state, sumState(thwgt_hig) AS thwgt_hig_state,
       sumState(thwgt_med) AS thwgt_med_state, sumState(thwgt_low) AS thwgt_low_state,
       sumState(bandwidth) AS bandwidth_state, sumState(traffic_in) AS traffic_in_state,
       sumState(traffic_out) AS traffic_out_state, sumState(session_block) AS session_block_state,
       browseTimeMergeState(b2) AS browse_time_state,
       sumState(sessions) AS sessions_state
FROM (
    SELECT
        timescale,
        epid,
        f_user,
        group_info,
        _adomoid,
        flags,
        d_flags,
        srcmac,
        srcip,
        srcintf,
        srcintfrole,
        srcuuid,
        srcinetsvc,
        dstip,
        dstmac,
        dstintf,
        dstintfrole,
        dstuuid,
        dstowner,
        dstcountry,
        app_group,
        rulename,
        vwlid,
        domain,
        hostname,
        catdesc,
        policymode,
        policyid,
        policytype,
        poluuid,
        policyname,
        service,
        clientdevicetags,
        accessproxy,
        saasname,
        fctuid,
        dvid,
        dev_src,
        devtype,
        maxMerge(avatar_state) AS avatar,
        maxMerge(epeuid_state) AS epeuid,
        maxMerge(logtime_state) AS logtime,
        maxMerge(threatlvl_state) AS threatlvl,
        sumMerge(threatweight_state) AS threatwgt,
        sumMerge(threatblock_state) AS threat_block,
        sumMerge(thwgt_cri_state) AS thwgt_cri,
        sumMerge(thwgt_hig_state) AS thwgt_hig,
        sumMerge(thwgt_med_state) AS thwgt_med,
        sumMerge(thwgt_low_state) AS thwgt_low,
        sumMerge(bandwidth_state) AS bandwidth,
        sumMerge(traffic_in_state) AS traffic_in,
        sumMerge(traffic_out_state) AS traffic_out,
        sumMerge(session_block_state) AS session_block,
        browseTimeMergeState(browse_time_state) AS b2,
        sumMerge(sessions_state) AS sessions
    FROM siem.fv_fgt_t_src_dst_5min_sp$SPID
    GROUP BY _adomoid, dvid, timescale,
         epid, f_user, group_info, devtype,
         srcmac, srcip, srcintf, srcintfrole, srcuuid, srcinetsvc, dev_src,
         dstip, dstmac, dstintf, dstintfrole, dstuuid, dstowner, dstcountry,
         app_group, rulename, vwlid, flags, d_flags, catdesc,
         policymode, policyid, policytype, poluuid, policyname,
         service, domain, hostname, fctuid,
         accessproxy, saasname, clientdevicetags
)
GROUP BY _adomoid, dvid, timescale,
     epid, f_user, group_info, devtype,
     srcmac, srcip, srcintf, srcintfrole, srcuuid, srcinetsvc, dev_src,
     dstip, dstmac, dstintf, dstintfrole, dstuuid, dstowner, dstcountry,
     app_group, rulename, vwlid, flags, d_flags, catdesc,
     policymode, policyid, policytype, poluuid, policyname,
     service, domain, hostname, fctuid,
     accessproxy, saasname, clientdevicetags;

CREATE MATERIALIZED VIEW IF NOT EXISTS siem.fv_fgt_t_src_dst_day_mv_sp$SPID
TO siem.fv_fgt_t_src_dst_day_sp$SPID
AS SELECT dvid,
       fv_timescale_func(timescale, 28800, 0) AS timescale,
       epid,
       _adomoid,
       flags,
       d_flags,
       f_user,
       srcmac,
       srcip,
       srcintf,
       srcintfrole,
       srcuuid,
       srcinetsvc,
       dstip,
       dstmac,
       dstintf,
       dstintfrole,
       dstuuid,
       dstowner,
       dstcountry,
       group_info,
       dev_src,
       devtype,
       app_group,
       rulename,
       vwlid,
       domain,
       hostname,
       catdesc,
       policymode,
       policyid,
       policytype,
       poluuid,
       policyname,
       service,
       clientdevicetags,
       accessproxy,
       saasname,
       fctuid,
        maxState(avatar) AS avatar_state,
       maxState(epeuid) AS epeuid_state, maxState(logtime) AS logtime_state,
       maxState(threatlvl) AS threatlvl_state, sumState(threatwgt) AS threatweight_state,
       sumState(threat_block) AS threatblock_state,
       sumState(thwgt_cri) AS thwgt_cri_state, sumState(thwgt_hig) AS thwgt_hig_state,
       sumState(thwgt_med) AS thwgt_med_state, sumState(thwgt_low) AS thwgt_low_state,
       sumState(bandwidth) AS bandwidth_state, sumState(traffic_in) AS traffic_in_state,
       sumState(traffic_out) AS traffic_out_state, sumState(session_block) AS session_block_state,
       browseTimeMergeState(b2) AS browse_time_state,
       sumState(sessions) AS sessions_state
FROM (
    SELECT
        timescale,
        epid,
        f_user,
        group_info,
        _adomoid,
        flags,
        d_flags,
        srcmac,
        srcip,
        srcintf,
        srcintfrole,
        srcuuid,
        srcinetsvc,
        dstip,
        dstmac,
        dstintf,
        dstintfrole,
        dstuuid,
        dstowner,
        dstcountry,
        app_group,
        rulename,
        vwlid,
        domain,
        hostname,
        catdesc,
        policymode,
        policyid,
        policytype,
        poluuid,
        policyname,
        service,
        clientdevicetags,
        accessproxy,
        saasname,
        fctuid,
        dvid,
        dev_src,
        devtype,
        maxMerge(avatar_state) AS avatar,
        maxMerge(epeuid_state) AS epeuid,
        maxMerge(logtime_state) AS logtime,
        maxMerge(threatlvl_state) AS threatlvl,
        sumMerge(threatweight_state) AS threatwgt,
        sumMerge(threatblock_state) AS threat_block,
        sumMerge(thwgt_cri_state) AS thwgt_cri,
        sumMerge(thwgt_hig_state) AS thwgt_hig,
        sumMerge(thwgt_med_state) AS thwgt_med,
        sumMerge(thwgt_low_state) AS thwgt_low,
        sumMerge(bandwidth_state) AS bandwidth,
        sumMerge(traffic_in_state) AS traffic_in,
        sumMerge(traffic_out_state) AS traffic_out,
        sumMerge(session_block_state) AS session_block,
        browseTimeMergeState(browse_time_state) AS b2,
        sumMerge(sessions_state) AS sessions
    FROM siem.fv_fgt_t_src_dst_hour_sp$SPID
    GROUP BY _adomoid, dvid, timescale,
         epid, f_user, group_info, devtype,
         srcmac, srcip, srcintf, srcintfrole, srcuuid, srcinetsvc, dev_src,
         dstip, dstmac, dstintf, dstintfrole, dstuuid, dstowner, dstcountry,
         app_group, rulename, vwlid, flags, d_flags, catdesc,
         policymode, policyid, policytype, poluuid, policyname,
         service, domain, hostname, fctuid,
         accessproxy, saasname, clientdevicetags
)
GROUP BY _adomoid, dvid, timescale,
     epid, f_user, group_info, devtype,
     srcmac, srcip, srcintf, srcintfrole, srcuuid, srcinetsvc, dev_src,
     dstip, dstmac, dstintf, dstintfrole, dstuuid, dstowner, dstcountry,
     app_group, rulename, vwlid, flags, d_flags, catdesc,
     policymode, policyid, policytype, poluuid, policyname,
     service, domain, hostname, fctuid,
     accessproxy, saasname, clientdevicetags;

ALTER TABLE siem.fv_fgt_t_src_dst_day_mv_sp$SPID MODIFY COMMENT '$VERSION';
